spring:
  # 数据源配置@Apollo
  #datasource:
    #username: xs_cc
    #password: xs_cc
    #url: jdbc:oracle:thin:@10.100.2.79:1521:ifp
    #driver-class-name: oracle.jdbc.OracleDriver
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cc?serverTimezone=UTC
    username: root
    password: 123456
    # 错误配置
    # Redis配置
  redis:
    host: 127.0.0.1
    port: 6379
      ### 连接超时时间（毫秒）
    timeout: 60000
    #password: 123456
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        ##连接池最大阻塞等待时间，若使用负值表示没有限制
        max-wait: 1
        ##连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0

server:
  # 服务端口
  port: 7003


mybatis:
  type-aliases-package: com.example.wyexercise.business
  mapper-locations: classpath:mapper/*.xml

cc:
  batch:
    sendPath: D:/template/7144120211201103444.xls